### ISSUE TITLE
Add ESP8266

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/nixie-counter#4]

**Comment by rnestler** [comment]
Huh you want an ESP8266 *and* the bluepill?

**Comment by dbrgn** [comment]
The blue pill does not have any networking. How do you transmit the data to the internet? :slightly_smiling_face: 

(Blue pill, 'cause Rust :crab: I think native ESP8266 support still isn't that good. I'd use the ESP as a serial modem.)

**Comment by rnestler** [comment]
~Why not just use an nRF module then? https://www.nordicsemi.com/Products/Low-power-short-range-wireless They have good Rust support and have WiFi as well, right?~

Forget that. They only support [802.15.4](https://de.wikipedia.org/wiki/IEEE_802.15.4), which isn't WiFi but something different. But we could use something like https://github.com/nRF24/RF24Gateway, but I don't really know how it works.

**Comment by dbrgn** [comment]
There are a few WiFi modules with Rust support, but no drivers for the WiFi stack...

Here would be 2 experimental crates for ESP8266 over serial support:

- https://github.com/TheZoq2/esp01-rs
- https://github.com/laanwj/k210-sdk-stuff/tree/master/util/esp8266at

An alternative would be the RTL8710, but I doubt that the software support is better...

Ideally we'd have a native Rust WiFi driver for one of those boards.
