### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/nixie-counter#7]
@rnestler @ubruhin Does one of you have time to give this board a review? I think it should now be ready for ordering a prototype PCB.

For an overview, see the README file.

**Comment by ubruhin** [comment]
I didn't review it in detail, but some mounting holes in the PCB might be nice to have :)

And the "Made With LibrePCB" logo is missing :scream:

**Comment by dbrgn** [comment]
Oh, two very good points :smile:

**Comment by dbrgn** [comment]
Both fixed.
